---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-docker-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: ClusterSecretStore
  target:
    name: ghcr-docker-secret
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.image.pullSecretRemoteRef }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flights-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: ClusterSecretStore
  target:
    name: flights-secrets
  data:
    {{- with .Values.externalSecret.remoteRefs }}
    - secretKey: wair-domain
      remoteRef:
        key: {{ .wairDomain }}
    - secretKey: rair-domain
      remoteRef:
        key: {{ .rairDomain }}
    - secretKey: r2-access-key
      remoteRef:
        key: {{ .r2AccessKey }}
    - secretKey: r2-secret-key
      remoteRef:
        key: {{ .r2SecretKey }}
    - secretKey: r2-endpoint
      remoteRef:
        key: {{ .r2Endpoint }}
    {{- end }}
